language: java
deploy:
 skip_cleanup: true
 provider: heroku
 app: spark-example-mariaffs
 api_key:
    secure: V4XWfwIGuxYqk81TuWHcQFpZcirQExjYNhcUAjW4n/dflx10Q6RmzZt5JmTKV0FANggJqvPX4VMaq5B9iiJK35fB72xkKXAlXpyNc3OsTPmFFo+oufSDvAopQyp1ARyEY+bv20FVNq7ERqt1SmaAzA5InWYPP0cMhDHPaZSS7hkHbcpcrz8ISfpJKm9b7ZwERX7GgDRJKPTbdaevU9fNVW4oHF2TB5KW5AlyArNmpT0AellKy746HaAZH1sUsGOKFdWzFkxCK5xatlmuAiwyhT+6bRXxEpYL1dAvkhkkEKmwa13y+gpQaYZdF4Il7ivy6NW3ue1TLJf97M4/mlz30ow4Hq5ry1oJKH8C2o0FmwbSIqlTayS462JVoJTjhgCzlPdfNnedFatW0xH1soHyaBoeJ9GxNcjYQ6L3ytXyXBNJQbvCGByluMwQo6yrPoxKtlPp7/TcRJzpv6/Mamwn+e4zqqF8D02CU5Ar2j9EjBcGtCpQKjtxydiQx2ynHzalqBsJH/YGqN4Pwg3Xk0HTZNZ/BO9zaVNrpr+XjxbFnm5LorYJy2PUDUVLfyFrsBUnWNcIuL4TssxeDg++dTgsxNAnRLJHZTIY86UIByDkfvGuAASQiFj3z/EAM1Luqx3JIphwRYKsxNXZbOCcqlBfiPG8HbFTwG2dx7IiJDs58ek=
